# Generated by Django 6.0.1 on 2026-03-23 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_routelog_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routelog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="routelog",
            name="route_points",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="routelog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
