# Generated by Django 6.0.1 on 2026-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_liveheartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveheartbeat",
            name="battery_level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
